### ISSUE TITLE
start/pause my washer and dishwasher when remote start is activated

### ISSUE THREAD

**Issue by nicx** [hcpy2-0/hcpy#115]
Hi there,

currently trying this great project at my home. Got it running via docker, HA auto discovery is working for all sensors.

Now I am asking myself how to start a program when remote start is activated and the program is already configured? On my old cloud based integration I have a "button.siemens_sx678x36ue_68a40e400c55_start_pause" and "bosch_wav28m40_68a40e336ac6_start_pause" entity which I can just use in HA. 

As far as I understood I'll have to edit the corresponding feature in the devices.json, but how could I find out the correct one?

The only feature I can find which sound similar is

            "537": {
                "name": "BSH.Common.Command.PauseProgram"
            },

But I think this is not the right one... so any hints for me? Thanks! :)

**Comment by nicx** [comment]
any hint?

**Comment by Meatballs1** [comment]
I'm not sure we've seen the trigger to just start the current select program, or if I did I forgot and didn't doucment it. There is no BSH.Common.Command to start a program but I can see Abort etc.

You should be able to get the current selected program from `SelectedProgram` and feed that into the MQTT request with a template?

```
  - service: mqtt.publish
    metadata: {}
    data_template::
      topic: homeconnect/dishwasher/activeProgram
      payload: '[{"program": {{ states("sensor.dishwasher_selected_program") }} }]'
```

You might need to work on escaping the `{}` this is just a quick idea.

**Comment by nicx** [comment]
@Meatballs1 good idea, but my dishwasher decice has no sensor.dishwasher_selected_program

Any hints? :)

**Comment by Meatballs1** [comment]
If you are using the auto-discover it may not have it.

But there's a lot more examples of sensors in the wiki to be added manually to the HA configuration including the selected_program

**Comment by nicx** [comment]
@Meatballs1 just a short feedback: it works! :) here is my config if anybody need it:

mqtt.yaml:

```
- sensor:
    name: "Dishwasher Selected Program"
    unique_id: "dishwasher_selected_program"
    icon: mdi:dishwasher
    state_topic: "homeconnect/dishwasher/state"
    value_template: >
      {{ value_json.SelectedProgram |string }}
    device:
      identifiers: "dishwasher"
    availability:
      - topic: "homeconnect/LWT"
      - topic: "homeconnect/dishwasher/LWT"
    availability_mode: all

- sensor:
    name: "Washer Selected Program"
    unique_id: "washer_selected_program"
    icon: mdi:washing-machine
    state_topic: "homeconnect/washer/state"
    value_template: >
      {{ value_json.SelectedProgram |string }}
    device:
      identifiers: "washer"
    availability:
      - topic: "homeconnect/LWT"
      - topic: "homeconnect/washer/LWT"
    availability_mode: all
```

and for the HA automation this template works:

```
action: mqtt.publish
metadata: {}
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: homeconnect/dishwasher/activeProgram
  payload: "{\"program\": {{ states(\"sensor.dishwasher_selected_program\") }} }"
```

thanks @Meatballs1 for your help!

**Comment by nicx** [comment]
@Meatballs1 with version 0.3.0 the payload for the selected program changed from numeric to text. before it was something like "8126", now it is "Dishcare.Dishwasher.Program.Eco50". Can I publish the text payload in the same way for remote starting the dishwasher/washer?

**Comment by Meatballs1** [comment]
It should be happy with either integer or string now

**Comment by Sprinterfreak** [comment]
I have a Siemens SR45ZS11ME, and can confirm it working except for Favorite.
To achieve running program Kurz60 with options ExtraDry and IntensiveZone active, i use following Script to activate

```yaml
sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: homeconnect/dishwasher/activeProgram
      payload: >-
        [{"program": "Kurz60", "options":
        [{"uid":5126,"value":true},{"uid":4356,"value":true}] }]
alias: Remote Start
description: ""
```

Note the options parameter, which lists the set payloads for the option switches. Seems to be recognized by the device just fine. Sending just the program itself results in all options reset to their defaults.
