### ISSUE TITLE
Several parameters for dishwasher disappeared after 0.2 update

### ISSUE THREAD

**Issue by Smosia** [hcpy2-0/hcpy#129]
Looks like after 0.2 update some parameters disappeared in my mqtt broker.
Missing parameters:
MachineCareAndFilterCleaningReminder
RinseAidNearlyEmpty
SaltNearlyEmpty
RinseAidLack
SaltLack

I've use them in previous versions.
Could you please check them in new version of hcpy.
I don't use HomeAssistant Autodiscovery.

**Comment by Meatballs1** [comment]
I'm thinking they should come through on /events now. I've tried to model the events closer to the app as they are stateless and should appear with autodiscovery. But you could model them with as sensors if you like - I was considering a configuration option to toggle them as events or sensors.

**Comment by Meatballs1** [comment]
Its not set to `Retain` so I'm not 100% sure if an explorer will see it after its been published?

My logs:

```
app_1  | 2025-02-13 15:22:05.194216 dishwasher publish to homeconnect/dishwasher/event with {"Dishcare.Dishwasher.Event.SaltNearlyEmpty": "Off"}
app_1  | 2025-02-13 15:22:05.194524 dishwasher publish to homeconnect/dishwasher/event with {"Dishcare.Dishwasher.Event.RinseAidNearlyEmpty": "Present"}
```

![Image](https://github.com/user-attachments/assets/bb7e05bd-4908-4f99-bee5-113d23d75048)

If the dishwasher doesn't communicate the event it may not be seen. I think as events they are modelled  closely to homeconnect which shows them as notifications - but they're not a state of the device as such.

**Comment by alexanderek** [comment]
same issue, how can I change: RinseAidNearlyEmpty, SaltNearlyEmpty, RinseAidLack, SaltLack back to sensors?

**Comment by Meatballs1** [comment]
Cant remember if they came through as binary_sensor or sensors but they have three states so binary_sensor doesn't fit anymore.
Will look at adding a switch in the config probably but for now either roll back, or you can manually define them but note the `event` topic isn't retained across restarts etc:

```
sensor:
  - name: RinseAidLackTest
    device:
      identifiers:
        - dishwasher
      manufacturer: NEFF
      model: xyz
      sw_version: '5.1'
      name: dishwasher
    state_topic: homeconnect/dishwasher/event
    availability_mode: all
    availability:
      - topic: homeconnect/LWT
      - topic: homeconnect/dishwasher/LWT
    value_template: |-
      {% if 'Dishcare.Dishwasher.Event.RinseAidLack' in value_json %}
        {{ value_json['Dishcare.Dishwasher.Event.RinseAidLack'] }}
      {% else %}
        Off
      {% endif %}
```

**Comment by alexanderek** [comment]
Yes, they were binary sensors. I'm trying to convert my automations to events, but so far without success.

**Comment by Meatballs1** [comment]
Events are stateless so you would only really use them as triggers. If you share the yaml I could take a look at what you're trying to do

**Comment by alexanderek** [comment]
@Meatballs1  

I'm trying to set up notifications in TG for certain dishwasher events, but the automation doesn't trigger when an event occurs.

<details>
  <summary>Critical Event Notification in Dishwasher</summary>

```
alias: Critical Event Notification in Dishwasher
description: Sends notifications to Telegram about critical events and their resolution.
triggers:
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltlack
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltnearlyempty
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidlack
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidnearlyempty
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_bsh_common_event_lowwaterpressure
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainpumpblocked
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainingnotpossible
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_internalerror
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_lowvoltage
    trigger: event
  - event_type: >-
      event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_waterheatercalcified
    trigger: event
conditions:
  - condition: template
    value_template: "{{ trigger.event.data.event_types in ['Present', 'Confirmed', 'Off'] }}"
actions:
  - data:
      target:
        - ident_num
      message: |
        {% if trigger.event.data.event_types == "Off" %}
          {% if trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltlack" %}
            ✅ Issue resolved! Salt has been added to the dishwasher.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltnearlyempty" %}
            ✅ Issue resolved! Salt level is now sufficient.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidlack" %}
            ✅ Issue resolved! Rinse aid has been added.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidnearlyempty" %}
            ✅ Issue resolved! Rinse aid level is now sufficient.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_bsh_common_event_lowwaterpressure" %}
            ✅ Issue resolved! Water supply has been restored.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainpumpblocked" %}
            ✅ Issue resolved! The drain pump is no longer blocked.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainingnotpossible" %}
            ✅ Issue resolved! Drain function is now working properly.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_internalerror" %}
            ✅ Issue resolved! The internal error has been fixed, and the dishwasher is operating normally.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_lowvoltage" %}
            ✅ Issue resolved! Power supply is now stable.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_waterheatercalcified" %}
            ✅ Issue resolved! The water heater has been descaled.
          {% else %}
            ✅ Issue resolved! Unknown event has been completed.
          {% endif %}
        {% else %}
          {% if trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltlack" %}
            ⚠️ Warning! The dishwasher is out of salt. Please add salt.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_saltnearlyempty" %}
            ⚠️ Warning! The dishwasher is running low on salt. Please add salt.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidlack" %}
            ⚠️ Warning! The dishwasher is out of rinse aid. Please add rinse aid.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_rinseaidnearlyempty" %}
            ⚠️ Warning! The dishwasher is running low on rinse aid. Please add rinse aid.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_bsh_common_event_lowwaterpressure" %}
            ⚠️ Warning! Low water pressure in the dishwasher. Check the water supply.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainpumpblocked" %}
            ⚠️ Warning! The dishwasher drain pump is blocked. Check the pump.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_drainingnotpossible" %}
            ⚠️ Warning! The dishwasher cannot drain water. Check the drainage system.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_internalerror" %}
            ⚠️ Warning! Dishwasher internal error detected. Inspection required.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_lowvoltage" %}
            ⚠️ Warning! Low voltage detected. Check the dishwasher’s power supply.
          {% elif trigger.event.event_type == "event.bosch_dishwasher_403100517946037741_dishcare_dishwasher_event_waterheatercalcified" %}
            ⚠️ Warning! The dishwasher water heater is calcified. Descaling is required.
          {% else %}
            ⚠️ Warning! Unknown event detected in the dishwasher.
          {% endif %}
        {% endif %}
    action: notify.telegram
mode: single
```

**Comment by Meatballs1** [comment]
Ah, I think the `trigger.event` is for the HA internal events, rather than event entities. Its a whole confusing convention:

https://www.home-assistant.io/docs/configuration/events/

![Image](https://github.com/user-attachments/assets/27a06942-da4d-4370-add0-d737d48182d7)

I could trigger the event OK with just an entity state change, but the `trigger` properties didn't contain the `event_type` (https://www.home-assistant.io/docs/automation/templating/#state) and the `to_state` didn't include it either :(.

I managed to do this with a bit of a workaround (I have slightly older automation syntax than you as a few months out of date at the moment):

```yaml
alias: Critical Event Notification in Dishwasher
description: Sends notifications to Telegram about critical events and their resolution.
trigger:
  - platform: state
    entity_id:
      - event.dishwasher_dishcare_dishwasher_event_saltlack
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_rinseaidlack
      - event.dishwasher_dishcare_dishwasher_event_rinseaidnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_internalerror
      - event.dishwasher_dishcare_dishwasher_event_lowvoltage
      - event.dishwasher_dishcare_dishwasher_event_waterheatercalcified
    attribute: event_type
    to: Present
    id: present
  - platform: state
    entity_id:
      - event.dishwasher_dishcare_dishwasher_event_saltlack
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_rinseaidlack
      - event.dishwasher_dishcare_dishwasher_event_rinseaidnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_internalerror
      - event.dishwasher_dishcare_dishwasher_event_lowvoltage
      - event.dishwasher_dishcare_dishwasher_event_waterheatercalcified
    attribute: event_type
    to: "Off"
    id: "off"
    from: Present
  - platform: state
    entity_id:
      - event.dishwasher_dishcare_dishwasher_event_saltlack
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_saltnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_rinseaidlack
      - event.dishwasher_dishcare_dishwasher_event_rinseaidnearlyempty
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_drainpumpblocked
      - event.dishwasher_dishcare_dishwasher_event_internalerror
      - event.dishwasher_dishcare_dishwasher_event_lowvoltage
      - event.dishwasher_dishcare_dishwasher_event_waterheatercalcified
    attribute: event_type
    to: Confirmed
    id: confirmed
    from: Present
action:
  - data_template:
      message: |
        {% if trigger.id == "off" %}
          {% if trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_saltlack" %}
            ✅ Issue resolved! Salt has been added to the dishwasher.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_saltnearlyempty" %}
            ✅ Issue resolved! Salt level is now sufficient.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_rinseaidlack" %}
            ✅ Issue resolved! Rinse aid has been added.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_rinseaidnearlyempty" %}
            ✅ Issue resolved! Rinse aid level is now sufficient.
          {% elif trigger.entity_id == "event.dishwasher_bsh_common_event_lowwaterpressure" %}
            ✅ Issue resolved! Water supply has been restored.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_drainpumpblocked" %}
            ✅ Issue resolved! The drain pump is no longer blocked.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_drainingnotpossible" %}
            ✅ Issue resolved! Drain function is now working properly.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_internalerror" %}
            ✅ Issue resolved! The internal error has been fixed, and the dishwasher is operating normally.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_lowvoltage" %}
            ✅ Issue resolved! Power supply is now stable.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_waterheatercalcified" %}
            ✅ Issue resolved! The water heater has been descaled.
          {% else %}
            ✅ Issue resolved! Unknown event has been completed.
          {% endif %}
        {% else %}
          {% if trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_saltlack" %}
            ⚠️ Warning! The dishwasher is out of salt. Please add salt.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_saltnearlyempty" %}
            ⚠️ Warning! The dishwasher is running low on salt. Please add salt.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_rinseaidlack" %}
            ⚠️ Warning! The dishwasher is out of rinse aid. Please add rinse aid.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_rinseaidnearlyempty" %}
            ⚠️ Warning! The dishwasher is running low on rinse aid. Please add rinse aid.
          {% elif trigger.entity_id == "event.dishwasher_bsh_common_event_lowwaterpressure" %}
            ⚠️ Warning! Low water pressure in the dishwasher. Check the water supply.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_drainpumpblocked" %}
            ⚠️ Warning! The dishwasher drain pump is blocked. Check the pump.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_drainingnotpossible" %}
            ⚠️ Warning! The dishwasher cannot drain water. Check the drainage system.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_internalerror" %}
            ⚠️ Warning! Dishwasher internal error detected. Inspection required.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_lowvoltage" %}
            ⚠️ Warning! Low voltage detected. Check the dishwasher’s power supply.
          {% elif trigger.entity_id == "event.dishwasher_dishcare_dishwasher_event_waterheatercalcified" %}
            ⚠️ Warning! The dishwasher water heater is calcified. Descaling is required.
          {% else %}
            ⚠️ Warning! Unknown event detected in the dishwasher.
          {% endif %}
        {% endif %}
    action: notify.mobile_app_pixel_8a
mode: queued
max: 10

```

For testing purposes the following action in developer tools is useful rather than restarting devices etc:

```yaml
action: mqtt.publish
data:
  topic: homeconnect/dishwasher/event
  payload: "{\"Dishcare.Dishwasher.Event.RinseAidLack\":\"Present\"}"
```
