### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by Turbox35** [hcpy2-0/hcpy#134]
Hello, thanks for this very interesting project.
I would like to run it on my Synology using container manager or portainer on Raspberry, I see the dockerfile implemented but can't find docker-compose.yaml example file. 
My question can be stupid but how deploy it using docker?

**Comment by Meatballs1** [comment]
Just compose.yaml 

https://github.com/hcpy2-0/hcpy/blob/main/compose.yaml

**Comment by Meatballs1** [comment]
It doesn't need a lot as it's not exposing any ports and connects out to MQTT server and the devices.

**Comment by Turbox35** [comment]
I see but how Portainer or Container Manager will find the image as it is not described into 
"image: " ?

**Comment by Meatballs1** [comment]
```
---
services:
  app:
    build: .
    restart: on-failure
    volumes:
      - ./config:/app/config
```

The `build: .` means it looks in the current location to build the image itself
