### ISSUE TITLE
Missing switches

### ISSUE THREAD

**Issue by Dis90** [hcpy2-0/hcpy#156]
Hi,

Can you add these switches to HA AutoDiscovery?

```
Dishcare.Dishwasher.Setting.ExtraDry
Dishcare.Dishwasher.Option.HalfLoad
Dishcare.Dishwasher.Option.EcoDry
```

devices.json
```
            "4356": {
                "name": "Dishcare.Dishwasher.Setting.ExtraDry",
                "access": "readWrite",
                "available": "true",
                "refCID": "01",
                "refDID": "00"
            },

            "5134": {
                "name": "Dishcare.Dishwasher.Option.EcoDry"
            },
            "5124": {
                "name": "Dishcare.Dishwasher.Option.HalfLoad"
            },
```

**Comment by Meatballs1** [comment]
`ExtraDry` comes through automatically for me (`switch.dishwasher_dishcare_dishwasher_setting_extradry`). Is it coming through as a sensor/binary_sensor for you? 

The EcoDry/HalfLoad are options that are set when you activate a Program and therefore need to be sent in the MQTT publish message. They don't have a state so can't be tracked via MQTT. Although you could create a helper toggle that you use in any script/automation to enable them? 

The following would start Eco wash with EcoDry enabled afaik (its not an option on my dishwasher):

```
action: mqtt.publish
data:
  topic: homeconnect/dishwasher/selectedProgram
  payload: '[{"program":8196,"options":[{"uid":5134,"value":true}]}]'
```
