### ISSUE TITLE
Trying to create a "Start Selected Program" Button in Home Assistant

### ISSUE THREAD

**Issue by vfedetz** [hcpy2-0/hcpy#169]
I am having a hard time figuring out how to do the following with my Bosch 800 dishwasher:

I want to have a dashboard with a drop down that allows selection of the "SelectedProgram" with a button next to it that will start the program which I have selected.

I found this issue [here ](https://github.com/hcpy2-0/hcpy/issues/115)but I still cannot figure out how to do it (extreme Home Assistant noob here).

1. I have the HomeConnect2MQTT addon installed and configured.
2. I created the devices.json file on another machine and moved it into the addons_config directory in home assistant. Can see all of the dishwasher controls under devices.
3. Here is my configuration.yaml
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
 ```
3. Here is my mqtt.yaml
```
sensor:
  - name: "Dishwasher Selected Program"
    unique_id: "dishwasher_selected_program"
    icon: mdi:dishwasher
    state_topic: "homeconnect/dishwasher/state"
    value_template: >
      {{ value_json.SelectedProgram |string }}
    device:
      identifiers: "dishwasher"
    availability:
      - topic: "homeconnect/LWT"
      - topic: "homeconnect/dishwasher/LWT"
    availability_mode: all
```

4. Here is a script I was attempting to make which I am thinking is called by a button on the dashboard
```
action: mqtt.publish
metadata: {}
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: homeconnect/dishwasher/activeProgram
  payload: "{\"program\": {{ states(\"sensor.dishwasher_selected_program\") }} }"
```

Clicking the button on the dashboard doesn't seem to do anything. Sorry I am still very new to Home Assistant (not new to linux in general).

**Comment by vfedetz** [comment]
Under Developer Tools > States I can see the new sensor added, but it has a state of "Unknown"

![Image](https://github.com/user-attachments/assets/70ce0be4-fb69-4630-a844-88637e9d8925)

**Comment by Meatballs1** [comment]
If you have enabled HA Discovery you shouldn't need to add the sensor. It should exist as `select.dishwasher_bsh_common_root_selectedprogram`. There have been a few changes to the way hcpy has worked since that issue was raised.

The script should then be:

```
action: mqtt.publish
metadata: {}
data:
  evaluate_payload: false
  qos: 0
  retain: false
  topic: homeconnect/dishwasher/activeProgram
  payload: "{\"program\": {{ states(\"select.dishwasher_bsh_common_root_selectedprogram\") }} }"
```
