### ISSUE TITLE
 "LocalControlActive": true prevents remote commands

### ISSUE THREAD

**Issue by Meatballs1** [hcpy2-0/hcpy#44]
On my hood, if I manually turn it on, the app says Local operation is active and therefore the device cannot be controlled by the app. This appears to last for about 15s. We should receive a status update from the device such as:

```
app_1  | 2024-03-28 21:34:57.364309 hood {'LocalControlActive': True, 'ActiveProgram': 55307, 'VentingLevel': 0, 'IntensiveLevel': 0, 'ElapsedProgramTime': 18}
```

This prevents automation of other activities for that ~15s period - e.g. it will reject lights being turned on or off with a 403 error. This requires either manual delays in automation, of we need to queue delays when requesting changes in code.

**Comment by noxhirsch** [comment]
Just for the record: My two devices (dishwasher & cookprocessor from Bosch) don't have this.

**Comment by Meatballs1** [comment]
My dishwasher doesn't either, i should probably just drop a note in the wiki as it took me a while to work out what was going on.

**Comment by androidand** [comment]
I got the json using for my oven hcpy-login-chromedp, but I tried for a long time to connect to it locally with hc2mqtt.py, seems it responds to nothing. I noticed this in the Cloud API:

    ...
    "status": [
      {
        "key": "BSH.Common.Status.RemoteControlActive",
        "value": true,
        "name": "Remote Control"
      },
      {
        "key": "BSH.Common.Status.RemoteControlStartAllowed",
        "value": true,
        "name": "Remote Start"
      },
      {
        "key": "BSH.Common.Status.LocalControlActive",
        "value": false,
        "name": "Local operation active"
      },
     {
        "key": "BSH.Common.Status.OperationState",
        "value": "BSH.Common.EnumType.OperationState.Run",
        "name": "Operation state",
        "displayvalue": "Running"
      },
      ...
      
      So somehow local operation is false, but the app shows the local connection as active? How does this work, how to turn local operation on?
      
As I interpret it, local operation is the ability to communicate over the LAN with the appliance? Any ideas on how to turn it on? It does not change state if I turn on or off the oven manually.

**Comment by Meatballs1** [comment]
Afaik the localcontrolactive is a signal that the user is manually modifying the device with physical controls and therefore to reject any remote commands for a specified period.

**Comment by androidand** [comment]
Since the oven doesn't respond to ping, have you got some suggestion on how to troubleshoot the TLS connection to the appliance?

**Comment by VVakko** [comment]
I have the same issue with my hood Neff D96BMV5N5.
If I turn on the hood with a local button, then via MQTT I can’t even turn the lights on/off for 15 seconds, while "LocalControlActive" is true.
In the official app, while "LocalControlActive" is true – the on/off buttons for the hood and lights are greyed out and disabled.

**Comment by Meatballs1** [comment]
In automations I use the following conditionally execute an action to handle this, will add to wiki

```
if:
  - condition: state
    entity_id: binary_sensor.hood_bsh_common_status_localcontrolactive
    state: "on"
then:
  - wait_for_trigger:
      - entity_id:
          - binary_sensor.hood_bsh_common_status_localcontrolactive
        to: "off"
        trigger: state
    timeout:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
enabled: true
```
