### ISSUE TITLE
Is there already a HA_hcpy-addon, or can it at least be run directly under HA?

### ISSUE THREAD

**Issue by Oktonaut** [hcpy2-0/hcpy#49]
Hello everybody,
I have a Siemens oven which I would like to integrate locally into my Home Assistant (VM on a Synology DiskStation) without using the Home Connect Cloud.
I came across the Trammell Hudson's article about a year ago, but didn't know how to integrate it directly into HA.
It should be possible to run the Phyton scripts directly in HA, for example with [python_script](https://github.com/home-assistant/core/tree/dev/homeassistant/components/python_script) or [PythonScriptsPro](https://github.com/AlexxIT/PythonScriptsPro)?
Or what would be even better: Is there now a corresponding add-on (something like [HA_enoceanmqtt-addon](https://github.com/mak-gitdev/HA_enoceanmqtt-addon))?

**Comment by pmagyar** [comment]
Hello,

in my opinion the best way is to create a homeassistant addon.
I have read the documentation and played around a bit
https://developers.home-assistant.io/docs/add-ons/

<img width="1141" alt="image" src="https://github.com/hcpy2-0/hcpy/assets/58977600/b80ee7ac-111d-46dc-81be-e8b18d4c35da">

<img width="1086" alt="image" src="https://github.com/hcpy2-0/hcpy/assets/58977600/dce68272-25b7-4c31-b826-081e5e97ad05">

The configuration parameter will be passed as environment variables to the container. 
Thats the config.yaml for the example addon:
```
name: "Hello world"
description: "My first real add-on!"
version: "1.0.1"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  api_key: xxxxxx
  mqtt_host: localhost
  mqtt_port: 9999
schema:
  api_key: str
  mqtt_host: str
  mqtt_port: int
startup: services
ports:
  8000/tcp: 8000
```

If i understand all correctly, we have to do the following:

- [ ] create pipeline to build docker image (for multiple archs) and push to github ecr
- [ ] define config.yaml for addon. 
    - [ ] The addon has to communicate with mqtt and iot devices. (check https://developers.home-assistant.io/docs/add-ons/communication)
    - [ ] included all options of hc2mqtt.py

Does anyone have any comments or another idea?
